import os
import csv
import time
from datetime import datetime
import requests
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# 1. Setup & Auth
load_dotenv()
# We need permission to modify playlists
SCOPE = "playlist-modify-public"

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=os.getenv("SPOTIPY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIPY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIPY_REDIRECT_URI"),
    scope=SCOPE
))

def get_all_countries():
    """Fetches ALL countries using REST Countries API."""
    print("--- Fetching global country list ---")
    response = requests.get("https://restcountries.com/v3.1/all")
    return [c['name']['common'] for c in response.json()]

def get_top_tracks_for_country(country_name, limit=5):
    """Finds the official 'Top 50' playlist and returns the top N tracks."""
    query = f"Top 50 {country_name} official"
    results = sp.search(q=query, type='playlist', limit=1)
    
    if not results['playlists']['items']:
        return []

    playlist_id = results['playlists']['items'][0]['id']
    tracks = sp.playlist_items(playlist_id, limit=limit)
    
    track_data = []
    for item in tracks['items']:
        if item.get('track'):
            track_data.append({
                'uri': item['track']['uri'],
                'name': item['track']['name'],
                'artist': item['track']['artists'][0]['name'],
                'country': country_name
            })
    return track_data

def log_to_csv(track_data_list):
    """Appends the fetched tracks to a CSV log file."""
    filename = "global_track_history.csv"
    file_exists = os.path.isfile(filename)
    
    with open(filename, mode='a', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        # Write headers if the file is brand new
        if not file_exists:
            writer.writerow(["Date", "Country", "Artist", "Track Name", "URI"])
            
        date_str = datetime.now().strftime("%Y-%m-%d")
        for track in track_data_list:
            writer.writerow([date_str, track['country'], track['artist'], track['name'], track['uri']])
    print(f"📄 Logged {len(track_data_list)} tracks to {filename}")

def main():
    countries = get_all_countries()
    all_track_data = []
    
    print(f"Scanning {len(countries)} countries for Spotify Charts...")

    for country in countries:
        try:
            # Changed limit to 5
            tracks = get_top_tracks_for_country(country, limit=5)
            if tracks:
                all_track_data.extend(tracks)
                print(f"✅ Gathered Top 5 from {country}")
            # Respect rate limits
            time.sleep(0.1) 
        except Exception:
            # Many countries don't have official Spotify charts, we just skip them.
            pass

    # 2. Trigger the Logging Feature
    log_to_csv(all_track_data)

    # 3. Create the Weekly Playlist
    # Extract just the URIs and remove duplicates (in case a song is top 5 in multiple countries)
    unique_track_uris = list(set([t['uri'] for t in all_track_data]))
    user_id = sp.me()['id']
    
    date_str = datetime.now().strftime("%b %d, %Y")
    playlist = sp.user_playlist_create(
        user_id, 
        name=f"Global Top 5s - {date_str}", 
        description=f"The top 5 songs from every available country globally. Generated by bhaley1."
    )

    print(f"Pushing {len(unique_track_uris)} unique tracks to Spotify...")
    for i in range(0, len(unique_track_uris), 100):
        batch = unique_track_uris[i:i+100]
        sp.playlist_add_items(playlist['id'], batch)

    print(f"\n🚀 Success! Playlist '{playlist['name']}' created.")

if __name__ == "__main__":
    main()